name: run
on: []
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependency
        run: cd ${{github.workspace}} && node install
      - name: Run the Bot
        run: node ${{github.workspace}}
